# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: inference.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    List,
    Optional,
)

import betterproto


@dataclass(eq=False, repr=False)
class ChatMessage(betterproto.Message):
    role: str = betterproto.string_field(1)
    content: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class GenerationParams(betterproto.Message):
    max_tokens: int = betterproto.int32_field(1)
    temperature: float = betterproto.float_field(2)
    top_p: float = betterproto.float_field(3)
    top_k: int = betterproto.int32_field(4)
    do_sample: bool = betterproto.bool_field(5)
    repetition_penalty: float = betterproto.float_field(6)
    user: Optional[str] = betterproto.string_field(7, optional=True)


@dataclass(eq=False, repr=False)
class Usage(betterproto.Message):
    prompt_tokens: int = betterproto.int32_field(1)
    completion_tokens: int = betterproto.int32_field(2)
    total_tokens: int = betterproto.int32_field(3)


@dataclass(eq=False, repr=False)
class ClientMessage(betterproto.Message):
    """Wrapper for all client requests"""

    request_id: str = betterproto.string_field(1)
    completion: "CompletionRequest" = betterproto.message_field(2, group="payload")
    chat_completion: "ChatCompletionRequest" = betterproto.message_field(
        3, group="payload"
    )


@dataclass(eq=False, repr=False)
class CompletionRequest(betterproto.Message):
    prompt: str = betterproto.string_field(1)
    params: "GenerationParams" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class ChatCompletionRequest(betterproto.Message):
    messages: List["ChatMessage"] = betterproto.message_field(1)
    params: "GenerationParams" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class ServerMessage(betterproto.Message):
    """Wrapper for all server responses"""

    request_id: str = betterproto.string_field(1)
    chunk: "StreamChunk" = betterproto.message_field(2, group="payload")
    complete: "StreamComplete" = betterproto.message_field(3, group="payload")
    error: "ErrorResponse" = betterproto.message_field(4, group="payload")


@dataclass(eq=False, repr=False)
class StreamChunk(betterproto.Message):
    """Streaming token chunk (sent for each generated token)"""

    id: str = betterproto.string_field(1)
    created: int = betterproto.int64_field(2)
    model: str = betterproto.string_field(3)
    choice: "ChunkChoice" = betterproto.message_field(4)


@dataclass(eq=False, repr=False)
class ChunkChoice(betterproto.Message):
    index: int = betterproto.int32_field(1)
    delta: "ChunkDelta" = betterproto.message_field(2)
    finish_reason: Optional[str] = betterproto.string_field(3, optional=True)


@dataclass(eq=False, repr=False)
class ChunkDelta(betterproto.Message):
    role: Optional[str] = betterproto.string_field(1, optional=True)
    content: Optional[str] = betterproto.string_field(2, optional=True)


@dataclass(eq=False, repr=False)
class StreamComplete(betterproto.Message):
    """Final message when generation completes"""

    id: str = betterproto.string_field(1)
    created: int = betterproto.int64_field(2)
    model: str = betterproto.string_field(3)
    usage: "Usage" = betterproto.message_field(4)


@dataclass(eq=False, repr=False)
class ErrorResponse(betterproto.Message):
    """Error response"""

    code: int = betterproto.int32_field(1)
    message: str = betterproto.string_field(2)
    type: Optional[str] = betterproto.string_field(3, optional=True)
